apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tests.guestbook
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - clusters:
        selector:
          matchExpressions:
            - { key: environment, operator: Exists } # Filter in-cluster since it is defined as a secret.
            - key: environment
              operator: NotIn
              values: [prod]
        values:
          revision: dev
    - clusters:
        selector:
          matchExpressions:
            - key: environment
              operator: In
              values: [prod]
        values:
          revision: main
  template:
    metadata:
      name: 'tests.guestbook.{{name}}'
      annotations:
        argocd.argoproj.io/manifest-generate-paths: .;../values.yaml;
    spec:
      destination:
        namespace: '{{metadata.labels.fake-ns}}'
        name: '{{name}}'
      project: tests
      source:
        path: helm-guestbook
        repoURL: https://github.com/argoproj/argocd-example-apps.git
        targetRevision: HEAD
        helm:
          releaseName: guestbook
          ignoreMissingValueFiles: true
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - FailOnSharedResource=true
          - ApplyOutOfSyncOnly=false
          - RespectIgnoreDifferences=true
